In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
dataset=pd.read_csv('AmesHousing.csv')

In [3]:
df=pd.DataFrame(dataset)

In [4]:
df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,...,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2926,2927,923276100,20,RL,NaN,8885,Pave,NaN,IR1,Low,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2927,2928,923400125,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2928,2929,924100070,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2929,2930,924151050,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [5]:
df['Alley'].isnull().sum(),df['Misc Feature'].isnull().sum()

(2732, 2824)

In [6]:
df.drop(['Alley','Misc Feature'],axis=1,inplace=True)

In [7]:
df

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,...,0,0,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,...,0,0,NaN,NaN,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,...,0,0,NaN,GdPrv,0,3,2006,WD,Normal,142500
2926,2927,923276100,20,RL,NaN,8885,Pave,IR1,Low,AllPub,...,0,0,NaN,MnPrv,0,6,2006,WD,Normal,131000
2927,2928,923400125,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,700,7,2006,WD,Normal,132000
2928,2929,924100070,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,4,2006,WD,Normal,170000
2929,2930,924151050,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,...,0,0,NaN,NaN,0,11,2006,WD,Normal,188000

In [8]:
for column in df.columns:
    tot=df[column].isnull().sum()
    if tot>0:
        print(column+":",tot)

Lot Frontage: 490
Mas Vnr Type: 1775
Mas Vnr Area: 23
Bsmt Qual: 80
Bsmt Cond: 80
Bsmt Exposure: 83
BsmtFin Type 1: 80
BsmtFin SF 1: 1
BsmtFin Type 2: 81
BsmtFin SF 2: 1
Bsmt Unf SF: 1
Total Bsmt SF: 1
Electrical: 1
Bsmt Full Bath: 2
Bsmt Half Bath: 2
Fireplace Qu: 1422
Garage Type: 157
Garage Yr Blt: 159
Garage Finish: 159
Garage Cars: 1
Garage Area: 1
Garage Qual: 159
Garage Cond: 159
Pool QC: 2917
Fence: 2358

In [9]:
df.drop(['Order','PID','Mas Vnr Type','Fireplace Qu','Pool QC','Fence'],axis=1,inplace=True)

In [10]:
df

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,...,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,20,RL,141.0,31770,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,120,0,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,Reg,Lvl,AllPub,Corner,Gtl,...,0,0,0,0,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,80,RL,37.0,7937,Pave,IR1,Lvl,AllPub,CulDSac,Gtl,...,0,0,0,0,0,3,2006,WD,Normal,142500
2926,20,RL,NaN,8885,Pave,IR1,Low,AllPub,Inside,Mod,...,0,0,0,0,0,6,2006,WD,Normal,131000
2927,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,700,7,2006,WD,Normal,132000
2928,20,RL,77.0,10010,Pave,Reg,Lvl,AllPub,Inside,Mod,...,0,0,0,0,0,4,2006,WD,Normal,170000
2929,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,Mod,...,0,0,0,0,0,11,2006,WD,Normal,188000

In [11]:
for column in df.columns:
    tot=df[column].isnull().sum()
    if tot>0:
        print(column+":",tot)

Lot Frontage: 490
Mas Vnr Area: 23
Bsmt Qual: 80
Bsmt Cond: 80
Bsmt Exposure: 83
BsmtFin Type 1: 80
BsmtFin SF 1: 1
BsmtFin Type 2: 81
BsmtFin SF 2: 1
Bsmt Unf SF: 1
Total Bsmt SF: 1
Electrical: 1
Bsmt Full Bath: 2
Bsmt Half Bath: 2
Garage Type: 157
Garage Yr Blt: 159
Garage Finish: 159
Garage Cars: 1
Garage Area: 1
Garage Qual: 159
Garage Cond: 159

In [12]:
##Numerical And Categorical Features
num_features=[]
cat_features=[]
for column in df.columns:
    if df[column].dtype!='O':
        num_features.append(column)
    else:
        cat_features.append(column)

In [13]:
df[num_features].head()

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,...,210,62,0,0,0,0,0,5,2010,215000
1,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,140,0,0,0,120,0,0,6,2010,105000
2,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,393,36,0,0,0,0,12500,6,2010,172000
3,20,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,...,0,0,0,0,0,0,0,4,2010,244000
4,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,212,34,0,0,0,0,0,3,2010,189900

In [14]:
df[cat_features].head()

,MS Zoning,Street,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,...,Electrical,Kitchen Qual,Functional,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Sale Type,Sale Condition
0,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,...,SBrkr,TA,Typ,Attchd,Fin,TA,TA,P,WD,Normal
1,RH,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,...,SBrkr,TA,Typ,Attchd,Unf,TA,TA,Y,WD,Normal
2,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,...,SBrkr,Gd,Typ,Attchd,Unf,TA,TA,Y,WD,Normal
3,RL,Pave,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,...,SBrkr,Ex,Typ,Attchd,Fin,TA,TA,Y,WD,Normal
4,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,...,SBrkr,TA,Typ,Attchd,Fin,TA,TA,Y,WD,Normal

In [15]:
df['Garage Type'].unique()

array(['Attchd', 'BuiltIn', 'Basment', 'Detchd', nan, 'CarPort', '2Types'],
      dtype=object)

In [16]:
new_df=df[num_features]

In [17]:
new_df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,...,210,62,0,0,0,0,0,5,2010,215000
1,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,140,0,0,0,120,0,0,6,2010,105000
2,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,393,36,0,0,0,0,12500,6,2010,172000
3,20,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,...,0,0,0,0,0,0,0,4,2010,244000
4,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,212,34,0,0,0,0,0,3,2010,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,80,37.0,7937,6,6,1984,1984,0.0,819.0,0.0,...,120,0,0,0,0,0,0,3,2006,142500
2926,20,NaN,8885,5,5,1983,1983,0.0,301.0,324.0,...,164,0,0,0,0,0,0,6,2006,131000
2927,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,80,32,0,0,0,0,700,7,2006,132000
2928,20,77.0,10010,5,5,1974,1975,0.0,1071.0,123.0,...,240,38,0,0,0,0,0,4,2006,170000
2929,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,190,48,0,0,0,0,0,11,2006,188000

In [18]:
cols=[]
for column in num_features:
    tot=new_df[column].isnull().sum()
    if(tot>0):
        median_value=np.median(new_df[column].dropna())
        new_df[column].fillna(median_value,inplace=True)

In [19]:
cols

[]

In [20]:
new_df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,...,210,62,0,0,0,0,0,5,2010,215000
1,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,140,0,0,0,120,0,0,6,2010,105000
2,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,393,36,0,0,0,0,12500,6,2010,172000
3,20,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,...,0,0,0,0,0,0,0,4,2010,244000
4,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,212,34,0,0,0,0,0,3,2010,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,80,37.0,7937,6,6,1984,1984,0.0,819.0,0.0,...,120,0,0,0,0,0,0,3,2006,142500
2926,20,68.0,8885,5,5,1983,1983,0.0,301.0,324.0,...,164,0,0,0,0,0,0,6,2006,131000
2927,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,80,32,0,0,0,0,700,7,2006,132000
2928,20,77.0,10010,5,5,1974,1975,0.0,1071.0,123.0,...,240,38,0,0,0,0,0,4,2006,170000
2929,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,190,48,0,0,0,0,0,11,2006,188000

In [21]:
new_df.isnull().sum()

MS SubClass        0
Lot Frontage       0
Lot Area           0
Overall Qual       0
Overall Cond       0
Year Built         0
Year Remod/Add     0
Mas Vnr Area       0
BsmtFin SF 1       0
BsmtFin SF 2       0
Bsmt Unf SF        0
Total Bsmt SF      0
1st Flr SF         0
2nd Flr SF         0
Low Qual Fin SF    0
Gr Liv Area        0
Bsmt Full Bath     0
Bsmt Half Bath     0
Full Bath          0
Half Bath          0
Bedroom AbvGr      0
Kitchen AbvGr      0
TotRms AbvGrd      0
Fireplaces         0
Garage Yr Blt      0
Garage Cars        0
Garage Area        0
Wood Deck SF       0
Open Porch SF      0
Enclosed Porch     0
3Ssn Porch         0
Screen Porch       0
Pool Area          0
Misc Val           0
Mo Sold            0
Yr Sold            0
SalePrice          0
dtype: int64

In [22]:
new_df

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,...,210,62,0,0,0,0,0,5,2010,215000
1,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,140,0,0,0,120,0,0,6,2010,105000
2,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,393,36,0,0,0,0,12500,6,2010,172000
3,20,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,...,0,0,0,0,0,0,0,4,2010,244000
4,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,212,34,0,0,0,0,0,3,2010,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,80,37.0,7937,6,6,1984,1984,0.0,819.0,0.0,...,120,0,0,0,0,0,0,3,2006,142500
2926,20,68.0,8885,5,5,1983,1983,0.0,301.0,324.0,...,164,0,0,0,0,0,0,6,2006,131000
2927,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,80,32,0,0,0,0,700,7,2006,132000
2928,20,77.0,10010,5,5,1974,1975,0.0,1071.0,123.0,...,240,38,0,0,0,0,0,4,2006,170000
2929,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,190,48,0,0,0,0,0,11,2006,188000

In [23]:
X=new_df.iloc[:,:-1]
y=new_df['SalePrice']

In [24]:
##Splitting into training and testing dataset
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [25]:
X_train

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold
844,20,68.0,9017,7,5,1999,1999,0.0,560.0,0.0,...,666.0,0,35,0,0,0,0,0,9,2009
2730,150,68.0,1700,7,5,1980,1981,0.0,397.0,0.0,...,450.0,188,36,0,0,200,0,0,4,2006
2793,20,68.0,14781,8,5,2001,2002,178.0,0.0,0.0,...,748.0,198,150,0,0,0,0,0,8,2006
1187,20,85.0,11050,6,5,1968,1968,0.0,301.0,0.0,...,512.0,25,0,0,0,192,0,0,10,2008
2770,60,65.0,12438,6,5,1995,1995,68.0,0.0,0.0,...,473.0,413,91,0,0,0,0,0,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1638,190,195.0,41600,5,5,1969,1990,0.0,1047.0,0.0,...,828.0,144,0,0,0,0,0,0,11,2007
1095,60,68.0,7750,7,5,2002,2002,0.0,0.0,0.0,...,403.0,100,35,0,0,0,0,0,4,2008
1130,60,64.0,8791,6,5,2003,2003,0.0,503.0,0.0,...,673.0,216,56,0,0,0,0,0,5,2008
1294,50,81.0,7308,5,5,1920,1950,0.0,360.0,0.0,...,225.0,0,0,236,0,0,0,0,6,2008
860,85,60.0,7200,5,8,1972,2003,0.0,660.0,0.0,...,396.0,192,0,0,0,0,0,0,4,2009

In [26]:
X_test

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold
1357,70,68.0,5100,8,7,1925,1996,0.0,0.0,0.0,...,228.0,192,63,0,0,0,0,0,6,2008
2367,160,21.0,1890,6,7,1972,1972,380.0,282.0,0.0,...,264.0,0,0,0,0,0,0,0,7,2006
2822,60,62.0,7162,7,5,2003,2004,190.0,0.0,0.0,...,616.0,168,57,0,0,0,0,0,5,2006
2126,20,60.0,8070,4,5,1994,1995,0.0,588.0,0.0,...,0.0,0,0,0,0,0,0,0,8,2007
1544,30,50.0,7000,6,8,1926,1998,0.0,299.0,40.0,...,195.0,0,0,116,0,0,0,0,7,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2521,120,40.0,3876,8,5,1978,1978,0.0,652.0,526.0,...,484.0,133,60,0,0,0,0,0,7,2006
707,30,62.0,7404,4,6,1920,1950,0.0,0.0,0.0,...,288.0,0,0,128,0,0,0,0,11,2009
424,20,108.0,13173,9,5,2006,2007,300.0,1572.0,0.0,...,840.0,404,102,0,0,0,0,0,11,2009
69,20,75.0,9000,8,5,2008,2008,36.0,1078.0,0.0,...,750.0,144,168,0,0,0,0,0,4,2010
736,50,50.0,6000,6,6,1939,1950,0.0,0.0,0.0,...,280.0,45,0,0,0,0,0,0,5,2009

In [27]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error,r2_score

In [28]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [29]:
models={"Linear Regression":LinearRegression(),
        "Lasso":Lasso(),
        "Ridge":Ridge(),
        "ElasticNet":ElasticNet(),
        "SVR":SVR(),
        "KNeighborsRegressor":KNeighborsRegressor()}

In [30]:
for name,model in models.items():
    try:
        model.fit(X_train_scaled,y_train)
        y_pred=model.predict(X_test_scaled)
        mean_abs_error=mean_absolute_error(y_pred,y_test)
        r2Score=r2_score(y_pred,y_test)
        print(name,":")
        print("Mean Absolute Error: ",mean_abs_error)
        print("R2 Score: ",r2Score)
        print("---------------------------")
    except Exception as e:
        print(f"Model {name} failed with error: {str(e)}")

Linear Regression :
Mean Absolute Error:  21283.13816550069
R2 Score:  0.7930063779531881
---------------------------
Lasso :
Mean Absolute Error:  21282.307349680137
R2 Score:  0.7929638477603765
---------------------------
Ridge :
Mean Absolute Error:  21280.226165800697
R2 Score:  0.7929558429951503
---------------------------
ElasticNet :
Mean Absolute Error:  21147.338093534083
R2 Score:  0.7301318411345379
---------------------------
SVR :
Mean Absolute Error:  60803.37821581969
R2 Score:  -535757.2175159502
---------------------------
KNeighborsRegressor :
Mean Absolute Error:  20836.21255115962
R2 Score:  0.7912369081553667
---------------------------

Let's select the KNeighborsRegressor and apply hyperparameter tuning in it

In [31]:
from sklearn.model_selection import GridSearchCV
parameters={"n_neighbors":[3,5,7,9,11],
            "weights":['uniform','distance'],
            "metric":['minkowski','euclidean','manhattan']}
estimator=KNeighborsRegressor()
grid_search=GridSearchCV(estimator,parameters, cv=5, scoring='r2', n_jobs=-1, verbose=2)

In [32]:
grid_search.fit(X_train_scaled,y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

GridSearchCV(cv=5, estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid={'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             scoring='r2', verbose=2)

In [33]:
print(f"Best params found:{grid_search.best_params_}")
print(f"Best R2 score:{grid_search.best_score_}")

Best params found:{'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'distance'}
Best R2 score:0.8393065041113263

In [34]:
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")
print(f"R2 Score: {r2}")

Mean Absolute Error: 20836.21255115962
R2 Score: 0.8457855738112534